Style/ModuleFunction:
  Exclude:
    - bin/alpaca
Style/ClassVars:
  Exclude:
    - lib/alpacabuildtool/configuration.rb
AllCops:
  Exclude:
    - vendor/**/*
Lint/Eval:
  Exclude:
    - lib/alpacabuildtool/entities/xml_node.rb